# rename the file as config.toml to use it

version = "v0.2.0"
prefix = "?" # enter default prefix here
webhook = 977405120830664724 # webhook id here
errorchannel = 977405248748519444 # error channel id here
guildlogchannel = 977405248736519190 # guild join leave log channel id here
description = "I am bot" # enter a bot description
redisuri = "redis://foo.bar.com:12345" # Redis info for connection
postgresuri = "postgresql://user:password@host/database" # Postgresql info for connection
TOKEN = "ODU4MzM1NjYzNTcxOTkyNjE4.YNcpYQ.vXnLsRySx0sJBo-0D10xCue2X9s" # enter bot token (be careful not to leak it)
Owners = [1994005784, 399005990003] # ids of all owners - I like to do this so that I can give owner permissions to others at times without having to give them access to the application itself.

[github]
branch = "main" # github branch
source = "https://github.com/Zeus432/Horus" # github link to repo

[invite] # 3 variant invite links to bot
normal = "https://discord.com/api/oauth2/authorize?client_id=858335663571992618&permissions=67420289&scope=bot+applications.commands"
mod = "https://discord.com/api/oauth2/authorize?client_id=858335663571992618&permissions=1116922503303&scope=bot+applications.commands"
admin = "https://discord.com/api/oauth2/authorize?client_id=858335663571992618&permissions=8&scope=bot+applications.commands"

[lavalink] # Lavelink server info
host = "0.0.0.0"
port = 8080
password = "youshallnotpass"

[spotify] # Spotify Developer credentials
client_id = "<Client ID>"
client_secret = "<Client Secret>"

[restart] # don't edit this var, used for bot restarts
